version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  lint:
    docker:
      image: circleci/node:12.9-buster
    steps:
      - checkout
      - run:
          name: "Run lint on project"
          command: npm run lint

workflows:
  node-tests:
    jobs:
      - node/lint
      - node/test
